### ISSUE TITLE
Incorrect tokens in wallet

### ISSUE THREAD

**Issue by bcerecer** [martian-dao/aptos-web3.js#10]
I previously opened this ticket about the tokens not being accurate in wallet:
https://github.com/martian-dao/aptos-web3.js/issues/6

And now I'm reopening it as this hasn't been correctly resolved. 
1. Even though, you now take into account that there might be more DepositEvents than WithdrawEvents 
2. The way that you are taking this into account is not correct, the call creates duplicate tokens when 2 deposits are created and it only has 1 withdrawal. Ping me over if you need help
3. You don't take into account that `getEventStream` can only return 25 events, which ends up making the wallet return incorrect data if the wallet has more than 25 deposit/withdraw events respectively

**Comment by MartianSiddharth** [comment]
Thanks for pointing this out, we've created [this PR](https://github.com/martian-dao/aptos-web3.js/pull/18) addressing your request. Would be great to see your suggestions

**Comment by bcerecer** [comment]
Below is a workaround that handles the tokens properly using Maps for constant lookup time. Although, it still has one edge case, if the token's collection or name has the characters "::", it won't retrieve the correct data as I'm using that to generate the tokenIdString which is the key for the Map. Hope this helps out 

`
const getTokenIdString = (tokenId: TokenId) => {
  return `${tokenId.creator}::${tokenId.collection}::${tokenId.name}`;
};

const getTokenIdFromString = (tokenIdString: string): TokenId => {
  const splittedTokenId = tokenIdString.split("::", 3);
  return {
    creator: splittedTokenId[0],
    collection: splittedTokenId[1],
    name: splittedTokenId[2],
  };
};

  // returns a list of token IDs of the tokens in a user's account (including the tokens that were minted)
  private async getTokenIds(address: string) {
    const depositEvents = await this.getEventStream(
      address,
      "0x1::token::TokenStore",
      "deposit_events"
    );
    const depositEventsMap = new Map<string, number>();
    depositEvents.map((depositEvent: any) => {
      const tokenIdString = getTokenIdString(depositEvent.data.id);
      const value = depositEventsMap.has(tokenIdString)
        ? (depositEventsMap.get(tokenIdString) as number)
        : 0;
      depositEventsMap.set(tokenIdString, value + 1);
    });

    const withdrawEvents = await this.getEventStream(
      address,
      "0x1::token::TokenStore",
      "withdraw_events"
    );
    const withdrawEventsMap = new Map<string, number>();
    withdrawEvents.map((withdrawEvent: any) => {
      const tokenIdString = getTokenIdString(withdrawEvent.data.id);
      const value = withdrawEventsMap.has(tokenIdString)
        ? (withdrawEventsMap.get(tokenIdString) as number)
        : 0;
      withdrawEventsMap.set(tokenIdString, value + 1);
    });

    const tokenIds: TokenId[] = [];

    depositEventsMap.forEach((depositEventsNumber, tokenIdString) => {
      const matchingWithdrawalEventsNumber = withdrawEventsMap.has(
        tokenIdString
      )
        ? (withdrawEventsMap.get(tokenIdString) as number)
        : 0;
      if (depositEventsNumber > matchingWithdrawalEventsNumber) {
        tokenIds.push(getTokenIdFromString(tokenIdString));
      }
    });

    console.log("Returned tokens: ", JSON.stringify(tokenIds));
    return tokenIds;
  }

`

**Comment by MartianSiddharth** [comment]
We've updated the getTokenIds function and tested out the flow with 50+ NFTs. It's working fine. Let me know if you see anything that we missed. Thanks

**Comment by MartianSiddharth** [comment]
Closing this
