### ISSUE TITLE
Input Parameters not given in Example code in Readme[BUG]

### ISSUE THREAD

**Issue by 0xAnto** [martian-dao/aptos-web3.js#21]
**Describe the bug**
WalletClient class requires Faucet url and Node url as input parameters but they are not given in Example code in Readme
`const aptosWeb3 = require('@martiandao/aptos-web3.js');
const walletClient = new aptosWeb3.WalletClient();`
**To Reproduce**
While Copying the example code in Readme
**Expected behavior**
Faucet url and Node url need to be given as input parameters

**Comment by MartianSiddharth** [comment]
Thanks for pointing this out. Have updated the README.md file
