### ISSUE TITLE
Incorrect tokens in wallet

### ISSUE THREAD

**Issue by bcerecer** [martian-dao/aptos-web3.js#6]
Currently, the way that you check if a wallet has a token from 0x1::Token::TokenStore is checking DepositEvents and WithdrawalEvents as in [here](https://github.com/martian-dao/aptos-web3.js/blob/bip44/src/wallet_client.ts#L466), but this doesn't take into account a use case as:
- Deposit token 
- Withdrawal token
- Deposit token (same token)

In this case your code would say that the token is not present in wallet, even though it is. Code should take into consideration number of DepositEvents vs WithdrawalEvents (instead of expecting that there's gonna be one of each at most)

**Comment by MartianSiddharth** [comment]
Nice catch!
Added the changes to handle this!

**Comment by bcerecer** [comment]
Thanks for the quick changes

**Comment by bcerecer** [comment]
This is still being handled incorrectly
