### ISSUE TITLE
Properly handle error for getTokenBalanceForAccount

### ISSUE THREAD

**Issue by bcerecer** [martian-dao/aptos-web3.js#8]
Currently, [getTokenBalanceForAccount](https://github.com/martian-dao/aptos-web3.js/blob/a1cafe0de055eb5feeba747ba7a91e6ee541396d/src/token_client.ts#L300) doesn't do error validation as if the TokenStore hasn't been created for the wallet, it would throw an error coming from the aptosClient. Ideally, it should return a response with a .value of 0

**Comment by MartianSiddharth** [comment]
This part of the code belongs to Aptos, will let them handle it
