### ISSUE TITLE
Addresses not being consistent

### ISSUE THREAD

**Issue by bcerecer** [martian-dao/aptos-web3.js#9]
Not sure if this is Aptos or Martian issue, but I created a collection with a Martian wallet which appeared to have the address `0x054dd5fc72c8d8051061cb74d47eb9e30a36099a38bb45c2e656af6de7f0a607`, however, when I call martian's walletClient.getTokens it says the creator is `0x54dd5fc72c8d8051061cb74d47eb9e30a36099a38bb45c2e656af6de7f0a607`

Here are the addresses in the Aptos explorer:
https://explorer.devnet.aptos.dev/account/0x054dd5fc72c8d8051061cb74d47eb9e30a36099a38bb45c2e656af6de7f0a607
https://explorer.devnet.aptos.dev/account/0x54dd5fc72c8d8051061cb74d47eb9e30a36099a38bb45c2e656af6de7f0a607

And as you can see they are the wallet, but different addresses, which definitely causes problems such as retrieving the tokens would indicate the creator is another wallet than the one that is connected

**Comment by MartianSiddharth** [comment]
Thanks for pointing this out. Turns out we should be using .toShortString() instead of .toString()
We'll push the code for this soon

**Comment by MartianSiddharth** [comment]
This Issue is resolved in the above PR. Closing it
